export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SURVEY_ADD_ITEM = "SURVEY_ADD_ITEM";
export const SURVEY_REMOVE_ITEM = "SURVEY_REMOVE_ITEM";
export const SURVEY_EDIT_ITEM = "SURVEY_EDIT_ITEM";

